<p style='text-align:center'>
PSY 394U <b>Methods for fMRI</b>, Fall 2018


<img style='width: 300px; padding: 0px;' src='https://github.com/sathayas/JupyterfMRIFall2018/blob/master/Images/Placebo_Left.png?raw=true' alt='brain blobs'/>

</p>

<p style='text-align:center; font-size:40px; margin-bottom: 30px;'><b>Basics of Python coding</b></p>

<p style='text-align:center; font-size:18px; margin-bottom: 32px;'><b>September 10 - 17, 2018</b></p>

<hr style='height:5px;border:none' />

# Essential Unix commands
<hr style="height:1px;border:none" />

Before we get started with Python coding, I thought it is a good idea to learn a few essential Unix commands. Many coding tools and some software tools for neuroimaging can be interfaced by using Unix commands from a terminal. Although Unix is completely replaced by Linux, you can still use essential Unix commands on Linux and Mac OS to accomplish various operations (copying files, moving files, creating directories, etc.). So knowing a few Unix commands can be a useful asset.

For this exercise, please open a terminal (for Mac and Linux users). 

*If you are using a **Windows** computer, I highly recommend installing a Unix-like virtual machine (VM) on your computer. There is a distribution of VM called FSLvm from FSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Windows). You can follow its installation instructions.*

## `ls` command
You can type a command
```
ls -l
```
and you will see a detailed list of items (files & directories) under your current directory. For example,
```
PSYC-A06168:~ sh45474$ ls -l
total 0
drwxrwxr-x@  3 sh45474  2066930642   102 Oct 10  2016 Creative Cloud Files
drwx------+  4 sh45474  2066930642   136 Jun 29 14:23 Desktop
drwx------+ 11 sh45474  2066930642   374 Dec  4  2017 Documents
drwx------+ 11 sh45474  2066930642   374 Jul  2 22:31 Downloads
drwx------@ 61 sh45474  2066930642  2074 Sep 14  2017 Library
drwx------+  3 sh45474  2066930642   102 Mar 23  2016 Movies
drwx------+  4 sh45474  2066930642   136 Apr  1  2016 Music
drwx------+  7 sh45474  2066930642   238 Aug 19  2016 Pictures
drwxr-xr-x+  5 sh45474  2066930642   170 Mar 23  2016 Public
drwxr-xr-x   5 sh45474  2066930642   170 Mar 14  2017 SoftwareTools
drwxr-xr-x   9 sh45474  2066930642   306 Apr 11 12:27 nltk_data
drwxr-xr-x   3 sh45474  2066930642   102 Apr 25 21:42 scikit_learn_data
```

On this list, directories are denoted by **`d`** at the first character, whereas files are denoted by **`-`**.  Or, you can run **`ls`** command on its own, which gives just a list without details.
```
PSYC-A06168:~ sh45474$ ls
Creative Cloud Files	Library			Public
Desktop			Movies			SoftwareTools
Documents		Music			nltk_data
Downloads		Pictures		scikit_learn_data
```

You can also run the `ls` command from a Jupyter notebook document. To do so, you have to type an exclamation mark (**`!`**) before the command (indicating that this is a Unix shell command, as opposed to a Python command).

In [1]:
!ls -l ~

total 0
drwxrwxr-x@  3 sh45474  2066930642   102 Oct 10  2016 Creative Cloud Files
drwx------+  4 sh45474  2066930642   136 Jun 29 14:23 Desktop
drwx------+ 11 sh45474  2066930642   374 Dec  4  2017 Documents
drwx------+ 11 sh45474  2066930642   374 Jul  2 22:31 Downloads
drwx------@ 61 sh45474  2066930642  2074 Sep 14  2017 Library
drwx------+  3 sh45474  2066930642   102 Mar 23  2016 Movies
drwx------+  4 sh45474  2066930642   136 Apr  1  2016 Music
drwx------+  7 sh45474  2066930642   238 Aug 19  2016 Pictures
drwxr-xr-x+  5 sh45474  2066930642   170 Mar 23  2016 Public
drwxr-xr-x   5 sh45474  2066930642   170 Mar 14  2017 SoftwareTools
drwxr-xr-x   9 sh45474  2066930642   306 Apr 11 12:27 nltk_data
drwxr-xr-x   3 sh45474  2066930642   102 Apr 25 21:42 scikit_learn_data


Here I put a tilde (**`~`**) after `ls -l`. This is a shorthand notation of your home directory. If you run `ls -l` on Jupyter without a tilde, you will be a print out of the content of where your Jupyter notebook document is stored.

In [2]:
!ls -l

total 72
-rw-r--r--   1 sh45474  2066930642   5731 Jul 12 13:25 BasicPython.ipynb
drwxr-xr-x  15 sh45474  2066930642    510 Jul 11 15:46 Images
-rw-r--r--   1 sh45474  2066930642  23219 Jul 12 12:57 Intro.ipynb
-rw-r--r--   1 sh45474  2066930642    204 Jul 11 16:09 README.md


## `mkdir` command
You can create a directory with the **`mkdir`** command, followed by the name of the directory. Say, I want to create a directory called **`fMRI_stuff`** under my home directory, I can type
```
mkdir fMRI_stuff
```
Just to verify whether it was actually created, I run `ls -l` again.
```
PSYC-A06168:~ sh45474$ ls -l
total 0
drwxrwxr-x@  3 sh45474  2066930642   102 Oct 10  2016 Creative Cloud Files
drwx------+  4 sh45474  2066930642   136 Jun 29 14:23 Desktop
drwx------+ 11 sh45474  2066930642   374 Dec  4  2017 Documents
drwx------+ 11 sh45474  2066930642   374 Jul  2 22:31 Downloads
drwx------@ 61 sh45474  2066930642  2074 Sep 14  2017 Library
drwx------+  3 sh45474  2066930642   102 Mar 23  2016 Movies
drwx------+  4 sh45474  2066930642   136 Apr  1  2016 Music
drwx------+  7 sh45474  2066930642   238 Aug 19  2016 Pictures
drwxr-xr-x+  5 sh45474  2066930642   170 Mar 23  2016 Public
drwxr-xr-x   5 sh45474  2066930642   170 Mar 14  2017 SoftwareTools
drwxr-xr-x   2 sh45474  2066930642    68 Jul 12 13:32 fMRI_stuff
drwxr-xr-x   9 sh45474  2066930642   306 Apr 11 12:27 nltk_data
drwxr-xr-x   3 sh45474  2066930642   102 Apr 25 21:42 scikit_learn_data
```

And you can see it's there.

## `cd` command
To move from one directory to another, you can use the **`cd`** command. Its syntax is
```
cd [directory name]
```
where `[directory name]` is the location you want to move. We can move to the `fMRI_stuff` directory we created earlier by
```
cd fMRI_stuff
```
To verify if you are really there, you can use the **`pwd`** command you saw earlier.
```
PSYC-A06168:fMRI_stuff sh45474$ pwd
/Users/sh45474/fMRI_stuff
```


Note that your result is likely different from mine.

Now let's create a directory called **`Data`**, and under `Data`, let's create a directory called **`func`**.
```
mkdir Data
cd Data
mkdir func
```
Then let's move to `func`. 
```
cd func
```
The current directory is 
```
PSYC-A06168:func sh45474$ pwd
/Users/sh45474/fMRI_stuff/Data/func
```

At this point you can go back to `fMRI_stuff` (two directories above) by
```
cd ..
cd ..
```
or 
```
cd ../..
```
Here, double periods indicate one directory above.
```
PSYC-A06168:fMRI_stuff sh45474$ pwd
/Users/sh45474/fMRI_stuff
```

Let's say, you want to go back to `func` directory. You can do
```
cd Data/func
```
This way of addressing the directory is called a **relative path**, originating from the  directory you are currently in.

You can also go to the same directory by
```
cd /Users/sh45474/fMRI_stuff/Data/func
```
This way of addressing the directory is called an **absolute path**. This command works whichever directory you are currently in

The **path** is the address for a directory or a file. It can be relative or absolute.


## Other useful commands

There are other useful Unix commands. I will to over them whenever we use one of these.
<table>
<tr>
<th style="text-align:left">Command</th>
<th style="text-align:left">What it does</th>
<th style="text-align:left">Syntax</th>
</tr>
<tr>
<td style="text-align:left">`cat`</td><td style="text-align:left">Prints a text file on a screen</td><td style="text-align:left">cat [file name]</td>
</tr>
<tr>
<td style="text-align:left">`cp`</td><td style="text-align:left">Copies a file or a directory</td><td style="text-align:left">cp [original item] [copied item]</td>
</tr>
<tr>
<td style="text-align:left">`gzip`</td><td style="text-align:left">Compresses a file (.gz added)</td><td style="text-align:left">gzip [file]</td>
</tr>
<tr>
<td style="text-align:left">`gzip -d `</td><td style="text-align:left">Uncompresses a file (.gz removed)</td><td style="text-align:left">gzip -d [file].gz</td>
</tr>

<tr>
<td style="text-align:left">`more`</td><td style="text-align:left">Prints a text file on a screen (pagenated version)</td><td style="text-align:left">more [file name]</td>
</tr>
<tr>
<td style="text-align:left">`mv`</td><td style="text-align:left">Moves a file or a directory</td><td style="text-align:left">mv [origin] [target]</td>
</tr>
<tr>
<td style="text-align:left">`rm`</td><td style="text-align:left">Deletes a file</td><td style="text-align:left">rm [file name]</td>
</tr>
<tr>
<td style="text-align:left">`rmdir`</td><td style="text-align:left">Deletes a directory</td><td style="text-align:left">rmdir [directory name]</td>
</tr>
</table>



# Operators
<hr style="height:1px;border:none" />

## Math operators
In your Python shell, try typing the following.


In [5]:
2 + 2

4

This is a simple example of an expression. An expression is an instruction consisting of numbers (e.g., 2) and mathematical operators (e.g. +). Any space in an expression is ignored. In addition to (no pun intended) addition (`+`), there are other operators:

  * Addition: `+`
  * Subtraction: `-`
  * Multiplication: `*`
  * Integer division: `//`
  * Division: `/`
  * Remainder after division: `%`
  * Exponent: `**`
  
## Application

### Scenario 1
Now consider the following scenario. You bought lunch for 3 of your friends and yourself. Each person had a sandwich (`$`6.50) and a soda (`$`1.50). How much in total did you pay?

In this scenario, you pay `$`6.50 + `$`1.50 per person. Since there are 4 of you, you paid

In [6]:
(6.50+1.50)*4

32.0

### Scenario 2
Your fMRI experiment consists of 10 epochs of finger tapping (25s), and each epoch is followed by 25s of rest. Before the first epoch, there is 15s of rest. What is the total duration of this experiment (in s)?

In [7]:
15 + 10*(25 + 25)

515

### Scenario 3
If you have `$`20, how many sodas (`$`1.50 each) can you buy on a vending machine?

In [8]:
20 // 1.50

13.0

And what would be the remainder after you buy that many sodas?

In [10]:
20 % 1.50

0.5

### Exercise
1. **How many scans**. Say, you are given a pilot grant of `$`3,000 to scan subjects on an MRI scanner. You will be charged `$`435 for the MRI scan for each subject. How many subjects can you scan with your pilot grant? (Post the solution formula on Canvas)
2. **How many stimuli**. You are designing an experiment with two conditions: listening to a story in English (Condition 1) and in Spanish (Condition 2). Each condition is 15s long, and has to be followed by 25s of silence. Your experiment has to have the same number of both conditions, and has to be under 10 minutes. How many Conditions 1 and 2 can you include in your experiment? (Post the solution formula on Canvas)

## String operators
In addition to numerical data, Python can also handle text data, also known as strings. A string is a series of characters (including space), and often denoted with quotation marks (') or (").

In [13]:
'Hello!'

'Hello!'

If you forget quotation marks, then you will likely get an error message

In [14]:
Hello

NameError: name 'Hello' is not defined

These are examples of strings:
```python
'a', 'AA', 'Aaaargh!', 'Hello World!', '24', '24 x 7'
```

As you have already seen before, you can concatenate two strings with `+`. For example,


In [15]:
'Maroon' + '5'

'Maroon5'

You can also repeat string data with `*`. For example,

In [16]:
'Yum! ' * 3

'Yum! Yum! Yum! '

# Variables and lists
<hr style="height:1px;border:none" />

## Variables
When you write a program, it is easier to store your numerical and string data to variables. A variable can be considered as a box where you store your data. For example,


In [18]:
age = 23

This statement puts 23 into a variable called **`age`**. If you type the variable name, then you can see what's in it

In [19]:
age

23

You can store a string into a variable. For example, in the variable called **`name`**,

In [20]:
name = 'Hayasaka'

In [21]:
name

'Hayasaka'

You can use variables in numerical and string operations. For example,

In [22]:
age + 5

28

In [23]:
'My name is ' + name

'My name is Hayasaka'

You can update a variable by replacing its value. For example,

In [1]:
name = 'Hanson'

In [2]:
name

'Hanson'

In [26]:
age = 55

In [27]:
age

55

You can name a variable anyway you like, as long as you follow some simple rules.

  1. Variable names can contain only alphabets, numbers, and underscore (`_`).
  2. Variable names cannot start with a number.
  3. Variable names cannot contain a space
  4. Variable names are case sensitive. For example, **`Name`** and **`name`** are two different variables.
  5. You cannot use certain keywords reserved for Python.

|        |      |       |      |        |
|:--:    |:--:  |:--:   |:--:  |:--:    |
|and     |del   |finally|in    |print   |
|assert  |elif  |for    |is    |raise   |
|break   |else  |from   |lambda|return  |
|class   |except|global |not   |try     |
|continue|exec  |if     |or    |True    |
|def     |False |import |pass  |while   |
|        |      |       |      |yield   |
|        |      |       |      |        |

## Converting strings to numbers

You can convert a string to a number, if it consists of numbers. For example,

In [3]:
numApple = input("How many apples would you like ($1.25 each)? ")

How many apples would you like ($1.25 each)? 5


In this case, the variable **`numApple`** is a string.

In [4]:
numApple

'5'

Consequently, you will get an error if you do this:

In [5]:
total = 1.25 * numApple

TypeError: can't multiply sequence by non-int of type 'float'

You can avoid this by using the **`int()`** function to convert a numerical string into a number.

In [6]:
total = 1.25 * int(numApple)
total

6.25

You can also convert a number into a string variable by **`str()`** function. For example,

In [45]:
age = 23

In [47]:
print("I am " + str(age) + " years old.")

I am 23 years old.


You need to use the `str()` function. Otherwise you get an error.

In [48]:
print("I am " + age + " years old.")

TypeError: must be str, not int

## Lists

A list is like a collection of variables. A collection of numbers and/or strings can be stored in a list. Here are examples of lists:

In [28]:
memberNames = ['Paul', 'John', 'George', 'Ringo']

In [29]:
memberNames

['Paul', 'John', 'George', 'Ringo']

In [30]:
numberList = [1, 5, 23, 512, 1023.5]

In [31]:
numberList

[1, 5, 23, 512, 1023.5]

As you can see, a list is bounded by square brackets `[]`, with elements separated by commas (`,`). To access an individual item of a list, you can use an index inside square brackets. For example,

In [32]:
memberNames = ['Paul', 'John', 'George', 'Ringo', 'Yoko']

In [33]:
memberNames[0]

'Paul'

In [34]:
memberNames[4]

'Yoko'

Notice that the indices start from 0 (referring to the first item on the list) and end with 4 (or, the number of items minus 1). You can use the **`len()`** function to figure out how many items are in a list.

In [35]:
len(memberNames)

5

In Python, you can also use a negative index to access individual items on a list. A negative index starts from -1, the last item on the list.

In [11]:
fruits = ['apple', 'orange', 'banana', 'pineapple']

In [52]:
fruits[-1]

'pineapple'

In [53]:
fruits[-4]

'apple'

You can change the value of individual items on a list, just the same way as changing a variable.


In [12]:
fruits

['apple', 'orange', 'banana', 'pineapple']

In [13]:
fruits[2] = 'grape'

In [14]:
fruits

['apple', 'orange', 'grape', 'pineapple']

## Slicing a list

Now, you can access multiple items on a list, to generate a sublist. This is known as **slicing**. For example, in a list

In [8]:
animal = ['dog', 'cat', 'tiger', 'lion', 'moose', 'panda', 'bear']

you want to access a sublist consisting of `cat`, `tiger`, and `lion`. In that case, you can use

In [9]:
animal[1:4]

['cat', 'tiger', 'lion']

This sublist consists of items `animal[1]`, `animal[2]`, and `animal[3]`. But not `animal[4]`. Inside the square brackets (i.e., 1:4) is often referred as a ***slice*** (as opposed to an *index*, which is a single value). In a slice, the first number corresponds to where the slice starts, and the second number corresponds to one after the slice ends.

You can use negative numbers to define a slice too.

In [16]:
animal[-3:-1]

['moose', 'panda']

If the first number of a slice is zero, or the second number of the slice is the number of itmes in the list, you can omit those numbers. For example,

In [27]:
animal[:4]

['dog', 'cat', 'tiger', 'lion']

In [30]:
animal[-3:]

['moose', 'panda', 'bear']

### Exercise
1. **First five**. Say you have two lists, one for stimulus onset times (in seconds) and the other for conditions (congruent (`C`) or incongruent (`I`)). 
```python
onset = [15, 30, 45, 60, 90, 105, 120, 135, 150, 165, 180, 195, 210]
cond = ['C','C','I','C','I','C','I','C','I','C','I','I','I']
```
Write a slice to generate sublists for the first 5 stimulus times and conditions.
2. **Last four**. On the same lists above, write a slice to generate sublists for the last 4 stimulus times and conditions.

## Lists are objects

Python is know as an object oriented programming language. That means you will likely encounter some objects as you write codes. A list is an example of objects. An object, unlike a variable, are associated with **attributes** and **methods**. An attribute describes a characteristic or a property of an object. A method is a special function that can be applied to the object. I will not go into too much details, but it is suffice to say that, if you have a Python object, you can use methods associated with that object to perform certain operations.

## Useful methods for lists


A *method* is similar to a function, but it is associated with a particular list. There are a number of methods you can use for the list data type. Here are some examples.

### `index()` method

You can find a particular value in a list using the **`index()`** method. This method returns the index corresponding to the value. For example,


In [17]:
memberNames = ['Paul', 'John', 'George', 'Ringo']
memberNames.index('George')

2

In other words, the index for the value 'George' is 2. 


### `append()`, `insert()` and `remove()` methods

To add items to a list, the **`append()`** and **`insert()`** methods can be useful. The **`append()`** method adds an item at the end of the list.


In [18]:
memberNames = ['Paul', 'John', 'George', 'Ringo']
memberNames.append('Yoko')
memberNames

['Paul', 'John', 'George', 'Ringo', 'Yoko']

If you want to add an item to a particular location on the list, you can use the **`insert()`** method, with the location to be inserted specified. For example,

In [19]:
memberNames = ['Paul', 'John', 'George', 'Ringo']
memberNames.insert(1,'Yoko')
memberNames

['Paul', 'Yoko', 'John', 'George', 'Ringo']

To remove an item from a list, you can use the **`remove()`** method. For example,

In [20]:
mammal = ['cat', 'dog', 'panda', 'owl', 'giraffe']
mammal.remove('owl')
mammal

['cat', 'dog', 'panda', 'giraffe']


### `sort()` method

You can sort the items on a list with the **`sort()`** method. For example,


In [22]:
numbers = [-5, -15, 2, 250, 3, 18]
numbers.sort()
numbers

[-15, -5, 2, 3, 18, 250]

In [36]:
mammal = ['dog', 'cat', 'panda', 'lion', 'horse']
mammal.sort()
mammal

['cat', 'dog', 'horse', 'lion', 'panda']

### Exercise
1. **Updating the name list**. To the list of names
```python
lastNames = ['Albert', 'Brewer', 'Delgado', 'Ellsworth','Franco']
```
add another item **`Chu`**, in a way that the list is still alphabetical.

## Strings are like lists

Individual characters within a string can be referenced like a list. For example,

In [31]:
text = 'Python is fun!'
text[0]

'P'

In [32]:
text[-1]

'!'

In [33]:
text[:6]

'Python'

In [34]:
text[-4:]

'fun!'

If you have a list of strings, then you can get a substring of a particular element by using two indices. For example, the first 3 letters of the last item on the list can be accessed by

In [35]:
memberNames = ['Paul', 'John', 'George', 'Ringo']
memberNames[-1][:3]

'Rin'

# Conditions
<hr style="height:1px;border:none" />

## True or False?

In your program, you may encounter situations in which you need to evaluate conditions. For example:

  * Variable **`age`** is greater than 18
  * Variable **`animal`** is equal to **`'llama'`**
  * Whether a string **`'Alice'`** is in a list **`names = ['Aaron','Ada','Albert','Alice','Alister']`**

Conditions can be described by a set of comparison operators. When executed, conditions return **`True`** or **`False`**.

In [15]:
# Defining the variables
age = 29
animal = 'panda'

In [5]:
# if age equals 23
age == 23

False

In [6]:
# if age is greater than 21
age > 21

True

In [7]:
# if animal is 'llama'
animal == 'llama'

False

In [8]:
# if animal is 'panda'
animal == 'panda'

True

In [10]:
# if animal is not 'llama'
animal != 'llama'

True

Here are some common comparison operators for variables.

  * **`==`**: equals
  * **`!=`**: not equal to
  * **`>`**: greater than
  * **`>=`**: greater than or equal to
  * **`<`**: less than
  * **`<=`**: less than or equal to

Using a comparison operator, you can execute something only when the condition is satisfied with **`if`**.

In [16]:
if age>18:
    print('You are old enough to participate in the study.')

You are old enough to participate in the study.


You can also specify what to execute when the condition is not met with **`else`**.

In [17]:
if age>65:
    print('You are old enough to participate in the study.')
else:
    print('You did not meet the age criterion.')

You did not meet the age criterion.


If you want to evaluate a series of conditions, you can combine `else` and `if` into **`elif`**. For example,

In [22]:
score = 62
if score > 80:
    print('You passed.')
elif score > 60:
    print('Conditional pass.')
else:
    print('You failed.')

Conditional pass.


## In or not in?
If you have a list, you can examine whether a certain item is in the list with **`in`** or **`not in`** operators.

In [1]:
numList = [5, 10, 15, 20, 30, 40]
alphaList = ['A','C','G','H','J','Q']

In [19]:
# if 25 is in the list numList
25 in numList

False

In [20]:
# if 25 is NOT in the list numList
25 not in numList

True

In [21]:
# if 'N' is in the list alphaList
'N' in alphaList

False

### Exercise
1. **Letter grade**. Write an **`if ... elif ... else`** statement to evaluate the letter grade based on these criteria:
<table>
    <tr>
        <th>Score</th>
        <th>Grade</th>
    </tr>
    <tr>
        <td>90-100</td>
        <td>A</td>
    </tr>
    <tr>
        <td>80-89</td>
        <td>B</td>
    </tr>
    <tr>
        <td>65-79</td>
        <td>C</td>
    </tr>
    <tr>
        <td>0-64</td>
        <td>F</td>
    </tr>
</table>

# `for` loops
<hr style="height:1px;border:none" />

## Repeat!

If you want to perform something a number of times, then you can use a **`for`** loop. Here is a simple example.

In [3]:
idList = []
for i in range(1,10):
    tmpID = '%04d' % i
    idList.append(tmpID)

In [4]:
idList

['0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009']

This simple code generated a series of subject IDs (as strings), as you can see.

In general, here is the syntax of a **`for`** loop.
```
for [iterator variable] in [list or other iterator object]:
    [Block of codes to be executed]
```

Here, the `[iterator variable]` takes a single value in a sequence of possible values in the `[list or other iterator object]`. In our example above, variable **`i`** takes a sequence of values specified in the **`range()`** function. The `range()` function is useful in generating a sequence of integers.

In [6]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
list(range(0,21,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

Inside the `for` loop is the `[Block of codes to be executed]`. This block will be executed multiple times, each with a different value of the `[iterator variable]`. In our example, 
```python
    tmpID = '%04d' % i
    idList.append(tmpID)
```
is executed with different values of `i` each time.

## Nested `for` loops

It is possible to have two `for` loops one within another. The iterator variable iterates over the inner `for` loop first, then the outer `for` loop. Here is an example generating subject IDs (5 subjects) and runs (3 runs per subject) for an experiment.

In [9]:
expList = []
for iSubj in range(1,6):
    for iRun in range(1,4):
        tmpID = 'subj' + '%04d' % iSubj
        tmpRun = 'run' + '%03d' % iRun
        expList.append(tmpID+'-'+tmpRun)

In [10]:
expList

['subj0001-run001',
 'subj0001-run002',
 'subj0001-run003',
 'subj0002-run001',
 'subj0002-run002',
 'subj0002-run003',
 'subj0003-run001',
 'subj0003-run002',
 'subj0003-run003',
 'subj0004-run001',
 'subj0004-run002',
 'subj0004-run003',
 'subj0005-run001',
 'subj0005-run002',
 'subj0005-run003']

### Exercise
1. **Rolling dice**. Assume you roll two dice, and calculate the sum of the resulting numbers. You want to make a list of all possible outcomes. For example,
```
(1, 1) = 2
(1, 2) = 3
. . .
(1, 6) = 7
(2, 2) = 4
(2, 3) = 5
. . .
```
and so on. In your table, you don't have to list redundant outcomes. For example, you don't list (5, 2) = 7, since this is already represented by (2, 5) = 7.

# Functions
<hr style="height:1px;border:none" />

## What is a function?
In math and computer science, functions are often referred as black boxes. This is because, when an input is given, a function performs a certain operation (perhaps unbeknownst to the user) and returns an output.

<img src="https://github.com/sathayas/JupyterfMRIFall2018/blob/master/Images/function_schematic.png?raw=true" alt="Function schematic" style="width: 250px; float: center;"/>

Think about some mathematical functions, such as `cos`, `log`, or `exp`. There are a number of functions that have already written (by someone else) in various libraries in Python. To run such a function, you need to import the library, then call the function. For example, let's import a random number generator function called **`randint()`** in the library **`random`**.

In [11]:
import random
for i in range(10):
    print(random.randint(1,10))

5
5
1
9
7
7
7
9
2
7


## Writing your own function

If you know you perform certain calculation or operations multiple times in your program, you can also write your own functions. For example, say you want to convert a temperature from Fahrenheit (the input parameter, **`tempF`**) to the temperature in Celsius, and returns it. You write a function **`FtoC`** for that purpose. 

In [12]:
def FtoC(tempF):
    tempC = (tempF - 32) * (5/9)
    return tempC

Once the function has been executed, you can call it in your code.

In [14]:
print('90F is equivalent to %4.1f in Celsius' % FtoC(90))

90F is equivalent to 32.2 in Celsius


In [19]:
print('Fahrenheit\tCelsius')
for i in range(-40,121,10):
    print('   %3d' % i, end='')
    print('\t\t', end='')
    print(' %5.1f' % FtoC(i))


Fahrenheit	Celsius
   -40		 -40.0
   -30		 -34.4
   -20		 -28.9
   -10		 -23.3
     0		 -17.8
    10		 -12.2
    20		  -6.7
    30		  -1.1
    40		   4.4
    50		  10.0
    60		  15.6
    70		  21.1
    80		  26.7
    90		  32.2
   100		  37.8
   110		  43.3
   120		  48.9


### Exercise
1. **Truncating a string**. Write a function that takes a string as the input. This function evaluate the length of the input string, and if it is longer than 5 characters, it returns only the first 5 characters of the input. Otherwise, the entire input string is returned.

## Local variables
Variables defined inside a function are only available inside the function. You cannot use those variables later outside the function. For example,

In [20]:
initScore = 55
finalScore = 72
def SomeScore(score):
    tmpScore = score + 25
    finalScore = tmpScore * 2
    print('Variable tmpScore inside the function: %d' % tmpScore)
    print('Variable finalScore inside the function: %d' % finalScore)
    
SomeScore(initScore)

Variable tmpScore inside the function: 80
Variable finalScore inside the function: 160


In [21]:
finalScore

72

In [22]:
tmpScore

NameError: name 'tmpScore' is not defined

Notice that the variable **`finalScore`** used inside the function is different from the variable **`fianlScore`** defined earlier. Variables inside a function are referred as **local variables**, and they exist only while the function is executed.

As you saw in the example, you can name a local variable the same name as another variable outside the function. However, this may cause a confusion later, so I recommend not to do that.

## Calling a function you have written before

If you have previously written a function to do something before, then you can use that function in another program. In other words, you don't have to re-write the function. Say you have a program called **`PrintRandom.py`**, and in it, there is a function called **`print_randint`**.
```python
import random

def print_randint(nInt):
    for i in range(nInt):
        print(random.randint(0,9), end='')
    print()
```
This function take an integer as an input. Then it prints out a series of random digits of the length specified by the input. Say, you have this function under the **`functions`** directory under your current directory. (This is true for those running the Jupyter notebook version of this document). Then you can call this function by

In [4]:
import sys
sys.path.append('functions')

from PrintRandom import print_randint
print_randint(5)

36534


The first two lines of codes are needed to add the directory **`function`** into **`sys.path`**, a list of directories where Python looks for functions to be run.

You can also call the function as:

In [5]:
import PrintRandom
PrintRandom.print_randint(8)

26458587


This notation means that you are calling the function **`print_randint()`** under the library **`PrintRandom`**. 

# For more details...
<hr style="height:1px;border:none" />

If you would like to learn more on Python coding, you can take a look at the notes from my [Intro Python coding class](https://github.com/sathayas/JupyterPythonFall2017/blob/master/README.md).

